services:
  wheeler-keeper:
    image: ghcr.io/jlleongarcia/wheeler-keeper:latest
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_default_superuser &&
             python manage.py collectstatic --noinput &&
             gunicorn wheeler_keeper.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped
    ports:
      - "8200:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wheeler_keeper_db
      - POSTGRES_USER=wheeler_keeper_user
      - POSTGRES_PASSWORD=wheeler_keeper_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume: