# Generated by Django 4.2.7 on 2025-10-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('moto', 'Moto'), ('coche', 'Coche'), ('furgoneta', 'Furgoneta'), ('autocaravana', 'Autocaravana'), ('camion', 'Camión')], help_text='Selecciona el tipo de vehículo', max_length=20, verbose_name='Tipo de vehículo')),
                ('marca', models.CharField(help_text='Marca del vehículo (ej: BMW, Honda, Mercedes)', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo específico del vehículo', max_length=100, verbose_name='Modelo')),
                ('año', models.PositiveIntegerField(blank=True, help_text='Año de fabricación del vehículo', null=True, verbose_name='Año de fabricación')),
                ('matricula', models.CharField(blank=True, help_text='Número de matrícula (opcional)', max_length=20, null=True, verbose_name='Matrícula')),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, help_text='Kilometraje actual del vehículo', verbose_name='Kilometraje actual')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('propietario', models.ForeignKey(help_text='Usuario propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
