# Generated by Django 4.2.7 on 2025-10-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cambio de aceite motor, Cambio filtro aire', max_length=100, verbose_name='Nombre del mantenimiento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del mantenimiento', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('motor', 'Motor'), ('transmision', 'Transmisión'), ('frenos', 'Frenos'), ('neumaticos', 'Neumáticos'), ('suspension', 'Suspensión'), ('electrico', 'Sistema Eléctrico'), ('climatizacion', 'Climatización'), ('filtros', 'Filtros'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('intervalo_km', models.PositiveIntegerField(blank=True, default=0, help_text='Cada cuántos kilómetros se debe realizar (0 = no aplica)', verbose_name='Intervalo en kilómetros')),
                ('intervalo_meses', models.PositiveIntegerField(blank=True, default=0, help_text='Cada cuántos meses se debe realizar (0 = no aplica)', verbose_name='Intervalo en meses')),
                ('vehiculos_aplicables', models.CharField(choices=[('todos', 'Todos los vehículos'), ('moto', 'Solo motos'), ('coche', 'Solo coches'), ('furgoneta', 'Solo furgonetas'), ('autocaravana', 'Solo autocaravanas'), ('camion', 'Solo camiones')], default='todos', max_length=20, verbose_name='Vehículos aplicables')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo aparecerá en las listas', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(help_text='Fecha en que se realizó el mantenimiento', verbose_name='Fecha de realización')),
                ('kilometraje_realizacion', models.PositiveIntegerField(help_text='Kilómetros del vehículo cuando se realizó el mantenimiento', verbose_name='Kilometraje de realización')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo del mantenimiento en euros', max_digits=10, null=True, verbose_name='Costo')),
                ('taller', models.CharField(blank=True, help_text='Dónde se realizó el mantenimiento', max_length=100, verbose_name='Taller/Lugar')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre el mantenimiento', verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.tipomantenimiento', verbose_name='Tipo de mantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='maintenance.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-fecha_realizacion'],
            },
        ),
    ]
