# Generated by Django 4.2.7 on 2025-10-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_tipomantenimiento_registromantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervaloMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_km_personalizado', models.PositiveIntegerField(blank=True, default=0, help_text='Intervalo específico para este vehículo (0 = usar valor por defecto)', verbose_name='Intervalo en kilómetros (personalizado)')),
                ('intervalo_meses_personalizado', models.PositiveIntegerField(blank=True, default=0, help_text='Intervalo específico para este vehículo (0 = usar valor por defecto)', verbose_name='Intervalo en meses (personalizado)')),
                ('notas', models.TextField(blank=True, help_text="Razón de la personalización (ej: 'Motor turbo requiere cambios más frecuentes')", verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.tipomantenimiento', verbose_name='Tipo de mantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos_personalizados', to='maintenance.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Intervalo de Mantenimiento Personalizado',
                'verbose_name_plural': 'Intervalos de Mantenimiento Personalizados',
                'ordering': ['vehiculo', 'tipo_mantenimiento'],
                'unique_together': {('vehiculo', 'tipo_mantenimiento')},
            },
        ),
    ]
