# Generated by Django 4.2.7 on 2025-10-25 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0003_intervalomantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario único para el nuevo usuario', max_length=150, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico del solicitante', max_length=254, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(help_text='Nombre del solicitante', max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellidos del solicitante', max_length=150, verbose_name='Apellidos')),
                ('password_hash', models.CharField(help_text='Hash de la contraseña del usuario', max_length=128, verbose_name='Hash de contraseña')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado actual de la solicitud', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la solicitud', verbose_name='Fecha de solicitud')),
                ('fecha_procesado', models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación/rechazo', null=True, verbose_name='Fecha de procesado')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del administrador', verbose_name='Notas')),
                ('procesado_por', models.ForeignKey(blank=True, help_text='Usuario administrador que procesó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Registro',
                'verbose_name_plural': 'Solicitudes de Registro',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
