# Generated by Django 4.2.7 on 2025-10-26 18:47

from django.db import migrations


def actualizar_tipos_filtros(apps, schema_editor):
    """
    Actualiza los tipos de mantenimiento de filtros:
    - Elimina: Cambio de filtro habitáculo
    - Agrega: Cambio de filtro de aceite
    - Agrega: Cambio de filtro de polen
    """
    TipoMantenimiento = apps.get_model('maintenance', 'TipoMantenimiento')
    
    # Eliminar filtros de habitáculo existentes
    TipoMantenimiento.objects.filter(nombre__icontains='habitáculo').delete()
    
    # Crear nuevos tipos de filtros
    nuevos_filtros = [
        {
            'nombre': 'Cambio de filtro de aceite',
            'descripcion': 'Sustitución del filtro de aceite del motor',
            'categoria': 'filtros',
            'intervalo_km': 15000,
            'intervalo_meses': 12,
            'vehiculos_aplicables': 'todos',
            'activo': True
        },
        {
            'nombre': 'Cambio de filtro de polen',
            'descripcion': 'Sustitución del filtro de polen del habitáculo',
            'categoria': 'filtros',
            'intervalo_km': 15000,
            'intervalo_meses': 12,
            'vehiculos_aplicables': 'todos',
            'activo': True
        },
    ]
    
    for filtro_data in nuevos_filtros:
        TipoMantenimiento.objects.get_or_create(
            nombre=filtro_data['nombre'],
            defaults=filtro_data
        )


def revertir_tipos_filtros(apps, schema_editor):
    """
    Revierte los cambios: elimina los nuevos filtros y restaura el filtro habitáculo
    """
    TipoMantenimiento = apps.get_model('maintenance', 'TipoMantenimiento')
    
    # Eliminar los filtros agregados
    TipoMantenimiento.objects.filter(
        nombre__in=['Cambio de filtro de aceite', 'Cambio de filtro de polen']
    ).delete()
    
    # Restaurar filtro habitáculo
    TipoMantenimiento.objects.get_or_create(
        nombre='Cambio de filtro habitáculo',
        defaults={
            'descripcion': 'Sustitución del filtro del habitáculo',
            'categoria': 'filtros',
            'intervalo_km': 15000,
            'intervalo_meses': 12,
            'vehiculos_aplicables': 'todos',
            'activo': True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_userregistrationrequest'),
    ]

    operations = [
        migrations.RunPython(
            actualizar_tipos_filtros,
            revertir_tipos_filtros,
            hints={'maintenance.TipoMantenimiento': 'exact_table'}
        ),
    ]
