# Generated by Django 4.2.7 on 2025-10-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20251026_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromantenimiento',
            name='costo',
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='costo_mano_obra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de la mano de obra en euros', max_digits=10, null=True, verbose_name='Costo de mano de obra'),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='costo_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de repuestos y materiales en euros', max_digits=10, null=True, verbose_name='Costo de materiales'),
        ),
    ]
