# Generated by Django 4.2.7 on 2025-10-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_remove_registromantenimiento_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromantenimiento',
            name='costo_mano_obra',
        ),
        migrations.RemoveField(
            model_name='registromantenimiento',
            name='costo_materiales',
        ),
        migrations.RemoveField(
            model_name='registromantenimiento',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='registromantenimiento',
            name='tipo_mantenimiento',
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='costo_mano_obra_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del trabajo realizado en euros', max_digits=10, null=True, verbose_name='Costo total de mano de obra'),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='notas_generales',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre toda la sesión de mantenimiento', verbose_name='Notas generales'),
        ),
        migrations.CreateModel(
            name='ItemMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Filtro de aceite Mann W712, Aceite 5W30 Castrol, etc.', max_length=200, verbose_name='Descripción del ítem')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades utilizadas', verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo por unidad en euros', max_digits=8, verbose_name='Costo unitario')),
                ('notas', models.TextField(blank=True, help_text='Observaciones específicas de este ítem', verbose_name='Notas del ítem')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.registromantenimiento', verbose_name='Registro de mantenimiento')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.tipomantenimiento', verbose_name='Tipo de trabajo')),
            ],
            options={
                'verbose_name': 'Ítem de Mantenimiento',
                'verbose_name_plural': 'Ítems de Mantenimiento',
                'ordering': ['tipo_mantenimiento__nombre'],
            },
        ),
    ]
