# Generated by Django 4.2.7 on 2025-10-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_remove_registromantenimiento_costo_mano_obra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmantenimiento',
            name='notas',
        ),
        migrations.AlterField(
            model_name='itemmantenimiento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Ej: Filtro de aceite Mann W712, Aceite 5W30 Castrol, etc.', max_length=200, verbose_name='Descripción del ítem'),
        ),
    ]
