# Generated by Django 4.2.7 on 2025-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_remove_itemmantenimiento_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromantenimiento',
            name='iva_incluido',
            field=models.BooleanField(default=True, help_text='Marcar si los precios ya incluyen IVA. Si no está marcado, se añadirá 21% al total', verbose_name='IVA incluido (21%)'),
        ),
    ]
