# Generated by Django 4.2.7 on 2025-11-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0009_add_iva_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('tipo_alerta', models.CharField(choices=[('proximo_km', 'Próximo por kilometraje'), ('proximo_tiempo', 'Próximo por tiempo'), ('vencido_km', 'Vencido por kilometraje'), ('vencido_tiempo', 'Vencido por tiempo')], max_length=20, verbose_name='Tipo de alerta')),
                ('kilometraje_notificado', models.PositiveIntegerField(help_text='Kilometraje del vehículo al momento de la notificación', verbose_name='Kilometraje cuando se notificó')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.tipomantenimiento', verbose_name='Tipo de mantenimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_mantenimiento', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Notificación de Mantenimiento',
                'verbose_name_plural': 'Notificaciones de Mantenimiento',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
