# Generated by Django 4.2.7 on 2025-12-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_notificacionmantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationrequest',
            name='google_id',
            field=models.CharField(blank=True, help_text='ID único de Google del usuario', max_length=255, null=True, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='google_picture',
            field=models.URLField(blank=True, help_text='URL de la foto de perfil de Google', null=True, verbose_name='Foto de Google'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='registration_type',
            field=models.CharField(choices=[('manual', 'Registro Manual'), ('google', 'Registro con Google')], default='manual', help_text='Método usado para el registro', max_length=20, verbose_name='Tipo de registro'),
        ),
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Hash de la contraseña del usuario', max_length=128, null=True, verbose_name='Hash de contraseña'),
        ),
    ]
