# Generated by Django 4.2.7 on 2026-03-10 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0011_userregistrationrequest_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomantenimiento',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Si está vacío, es un tipo global del sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_mantenimiento_propios', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddConstraint(
            model_name='tipomantenimiento',
            constraint=models.UniqueConstraint(fields=('propietario', 'nombre'), name='unique_tipo_mantenimiento_por_propietario'),
        ),
    ]
